hydra:
  run:
    dir: ${output_dir}
  output_subdir: ${output_dir}/code/hydra
  searchpath:
    - pkg://navsim.planning.script.config.common
  job:
    chdir: False

defaults:
  - default_common
  - default_dataset_paths
  - _self_

force_feature_computation: True
output_dir: ${metric_cache_path}/metadata
